services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: superuser
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin-container
    environment:
      - STORAGE_TYPE=mem
      - SELF_TRACING_ENABLED=true
      - SELF_TRACING_SAMPLE_RATE=1.0 # Adjust this value as needed (0.0 to 1.0)
      - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError # Set initial and maximum heap size
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data:
  pg_data:
